apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: l0mftlim1-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/l0mftlim1-dotnet-basic-gitops